version: 0.2

phases:
  install:
    commands:
      # Upgrade CLI
      - pip install --upgrade awscli

      # Needed for cypress
      - apt-get update
      - apt-get install -y libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 xvfb

      # Install dependencies
      - npm install
  pre_build:
    commands:
      # Runs cypress tests
      - npm test
  build:
    commands:
      # Run actual build.
      - npm run build
artifacts:
  type: zip
  base-directory: dist
  files:
      - '**/*'
